apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  FRONTEND_URL: {{ .Values.config.frontendUrl | quote }}
  JWT_EXPIRES_IN: {{ .Values.config.jwtExpiresIn | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.backend.port | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace }}
data:
  BACKEND_INTERNAL_URL: {{ .Values.config.backendInternalUrl | quote }}
