apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
